BookAuthorApp/Models/Entities/Book.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace BookAuthorApp.Models.Entities
{
    public class Book
    {
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        public String? Title { get; set; }
        public int PublicationYear { get; set; }

        public ICollection<Author> Authors { get; set; }
            = new List<Author>();
    }
}

BookAuthorApp/Controllers/AuthorController.cs
using BookAuthorApp.Models.Entities;
using BookAuthorApp.Models.ViewModels;
using BookAuthorApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace BookAuthorApp.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IBookRepository _bookRepository;
        public AuthorController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> CreateAsync([Bind(Prefix = "id")] int bookId)
        {
            var book = await _bookRepository.ReadAsync(bookId);
            if (book == null)
            {
                RedirectToAction("Index", "Book");
            }
            ViewData["Book"] = book;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int bookId, CreateAuthorVM author)
        {
            if (author != null)
            {
                var model = author.GetAuthorInstance();
                await _bookRepository.CreateAuthorAsync(bookId, model);
                return RedirectToAction("Details", "Book", new { id = bookId });
            }
            var book = _bookRepository.ReadAsync(bookId);
            ViewData["Book"] = book;
            return View(author);
        }
        public async Task<IActionResult> Edit([Bind(Prefix = "id")] int bookId, int authorId)
        {
            var book = await _bookRepository.ReadAsync(bookId);
            if (book == null)
            {
                return RedirectToAction("Index", "Book");
            }
            var author = book.Authors.FirstOrDefault(a => a.Id == authorId);
            if (author == null )
            {
                return RedirectToAction("Details", "Book");
            }
            var model = new EditAuthorVM()
            {
                Book = book,
                Id = author.Id,
                FirstName = author.FirstName,
                LastName = author.LastName
            };
            return View(model);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int bookId, EditAuthorVM authorVM)
        {
            if (ModelState.IsValid)
            {
                var author = authorVM.GetAuthorInstance();
                await _bookRepository.UpdateAuthorAsync(bookId, author);
                return RedirectToAction("Details", "Book", new { id = bookId});
            }
            authorVM.Book = await _bookRepository.ReadAsync(bookId);
            return View(authorVM);
        }

        public async Task<IActionResult> Delete([Bind(Prefix = "id")]int bookId, int authorId)
        {
            var book = await _bookRepository.ReadAsync(bookId);
            if(book == null)
            {
                return RedirectToAction("Index", "Book");
            }
            var author = book.Authors.FirstOrDefault(a => a.Id == authorId);
            if (author == null)
            {
                return RedirectToAction("Details", "Book", new { id = bookId });
            }
            var model = new DeleteAuthorVM()
            {
                Book = book,
                Id = author.Id,
                FirstName = author.FirstName,
                LastName = author.LastName
            };
            return View(model);
        }
        [HttpPost, ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int bookId, int authorId)
        {
            await _bookRepository.DeleteAuthorAsync(bookId, authorId);
            return RedirectToAction("Details", "Book", new { id = bookId });
        }
    }
}

BookAuthorApp/Controllers/BookController.cs
using BookAuthorApp.Models.Entities;
using BookAuthorApp.Models.ViewModels;
using BookAuthorApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookAuthorApp.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;
        public BookController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IActionResult> Index()
        {
            var allBooks = await _bookRepository.ReadAllAsync();
            var model = allBooks.Select(b =>
            new BookDetailsVM
            {
                Id = b.Id,
                Title = b.Title,
                PublicationYear = b.PublicationYear,
                NumberOfAuthors = b.Authors.Count
            });
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookVM book)
        {
            if (book != null)
            {
                var model = book.getBookInstance();
                await _bookRepository.CreateAsync(model);
                return RedirectToAction("Index");
            }
            return View(book);
        }
        public async Task<IActionResult> Details(int id)
        {
            var book = await _bookRepository.ReadAsync(id);
            if(book == null)
            {
                return RedirectToAction("Index", "Book");
            }
            var model = new BookDetailsVM()
            {
                Id = book.Id,
                Title = book.Title,
                PublicationYear = book.PublicationYear,
                NumberOfAuthors = book.Authors.Count,
                Authors = book.Authors
            };
            return View(model);
        }
    }
}

BookAuthorApp/Views/Book/Create.cshtml
@model BookAuthorApp.Models.ViewModels.CreateBookVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create Book</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
@*            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicationYear" class="control-label"></label>
                <input asp-for="PublicationYear" class="form-control" />
                <span asp-validation-for="PublicationYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookAuthorApp/Views/Book/Details.cshtml
@model BookAuthorApp.Models.ViewModels.BookDetailsVM

@{
    ViewData["Title"] = "Details";
}

<h1>Book Details</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Details">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" readonly class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" readonly class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicationYear" class="control-label"></label>
                <input asp-for="PublicationYear" readonly class="form-control" />
                <span asp-validation-for="PublicationYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfAuthors" class="control-label"></label>
                <input asp-for="NumberOfAuthors" readonly class="form-control" />
                <span asp-validation-for="NumberOfAuthors" class="text-danger"></span>
            </div>
            <div class="form-group">
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@if (Model != null)
{
    <h4>Authors</h4>
    <a asp-action="Create" asp-controller="Author" asp-route-id="@Model.Id">
        Add Author
    </a>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Authors != null)
            {
                @foreach (var author in Model.Authors)
                {
                    <tr>
                        <td>
                            @author.Id
                        </td>
                        <td>
                            @author.FirstName @author.LastName
                        </td>
                        <td>
                            <a asp-action="Edit" asp-controller="Author"
                       asp-route-id="@Model.Id" asp-route-authorId="@author.Id">Edit</a> |
                            <a asp-action="Delete" asp-controller="Author"
                       asp-route-id="@Model.Id" asp-route-authorId="@author.Id">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
}


    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

BookAuthorApp/Views/Book/Index.cshtml
@model IEnumerable<BookAuthorApp.Models.ViewModels.BookDetailsVM>

@{
    ViewData["Title"] = "Book List";
}

<h1>Book List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublicationYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfAuthors)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
             <td>
                @Html.DisplayFor(modelItem => item.Id)
             </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublicationYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfAuthors)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>